version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3400:3400'
    depends_on:
      - db
    env_file: .env
    working_dir: '/usr/src/app'
    environment:
      DB_HOST: 'db'
    stdin_open: true
    tty: true
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '8400:8400'
    depends_on:
      - app
  db:
    image: postgres:9.5
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "db-data:/var/lib/postgresql/data"
    restart: on-failure
volumes:
  db-data:
