defaults: &defaults
  tools:
    default: &default
      icon: selector.png

    rooms:
      <<: *default
      root: apps
      secret: abcde-12345

    greenlight:
      <<: *default
      root: gl
      secret: abcde-12345

development:
  <<: *defaults
  product_instance_guid: aada9378-4474-4676-ad7c-db583b43c8d7

test:
  <<: *defaults
  product_instance_guid: a27dfd1f-c372-4a05-a382-7fa782a53570

production:
  <<: *defaults
  product_instance_guid: 048a0d6c-2852-4117-9e32-b7a6c4baf69f
