defaults: &defaults
  tools:
    default: &default
      icon: selector.png

    rooms:
      <<: *default
      root: apps
      secret: abcde-12345
      oauth2_url: http://lti-dev/lti
      oauth2_key: 0fad3e29c110af4a6a57b88ae1d072dcdc131622520cff130feea0a06418dc50
      oauth2_secret: 84f647c6b06253b8a36383495b86f21a127de1bd5e0d9d60f84fad6d6307a0d8

    greenlight:
      <<: *default
      root: gl
      secret: abcde-12345

development:
  <<: *defaults
  product_instance_guid: aada9378-4474-4676-ad7c-db583b43c8d7

test:
  <<: *defaults
  product_instance_guid: a27dfd1f-c372-4a05-a382-7fa782a53570

production:
  <<: *defaults
  product_instance_guid: 048a0d6c-2852-4117-9e32-b7a6c4baf69f
